# MTH/CMSE 314
# IC12: Gram-Schmidt Orthogonalization Process
### <p style="text-align: right;"> &#9989; **Mikel Good** </p>

#### Goals
- Given a basis, find another basis step-by-step that is orthogonal or orthonormal.
- Write a code that takes a linearly independent set as an input and outputs an orthogonal set.
- Write a code that takes a set $S$ as an input and outputs an orthogonal basis for span($S$).

#### Please read the following before you begin: 

- <font color=#641e16> It is recommended that you complete the After-Class Assignments (ACs) before starting the In-Class Assignments (ICs),
    
- <font color=#641e16> Keep your lecture notes nearby for guidance!

- <font color=#641e16> Use class time to collaborate with your group and get help from instructors, as IC solutions will not be provided.

---
<font color='blue'> &#9989; **Do this:** Complete the following block of code to write a function that projects one vector onto another.

In [49]:
import numpy as np

In [81]:
def projection(v, u):
    u = np.array(u, dtype=float)
    v = np.array(v, dtype=float)
    if len(u) != len(v):
        raise ValueError("Vectors must have same dimension")

    y = np.dot(u, u)
    if y == 0:
        return np.zeros_like(u)   # or raise an error

    w = np.dot(v, u)
    return (w / y) * u


---
#### Now, answer the following questions.

<font color='blue'> &#9989;**Do this (BY HAND):** Implement the Gram-Schmidt orthogonalization process to find an **orthogonal basis** of $\mathbb{R}^3$ from the given set of linearly independent vectors $\{b_1=[1,1,1],\ b_2=[1,1,-2],\ b_3=[0,2,-1]\}$. And then make it **orthonormal**.   
    
Import a photo with your solutions or type in latex.

<font color='blue'> &#9989;**Do this (BY HAND):** Implement the Gram-Schmidt orthogonalization process to find an **orthogonal subset** of $\mathbb{R}^4$ from the given set of linearly independent vectors $\{b_1=[1,1,1,-1],\ b_2=[1,1,-2,0],\ b_3=[0,2,-1,4]\}$.
        
Import a photo with your solutions or type in latex.

<font color='blue'> &#9989;**Do this:** Now you will do the same problem above using python.

In [19]:
b1 = np.array([1, 1, 1, -1])
b2 = np.array([1, 1, -2, 0])
b3 = np.array([0, 2, -1, 4])

v1 = b1
v2 = b2 - (np.dot(b2, v1)/np.dot(v1,v1)) * v1
v3 = b3 - (np.dot(b3, v1)/np.dot(v1,v1)) * v1 - (np.dot(b3, v2)/np.dot(v2,v2)) * v2

In [20]:
print(v1, "\n", v2, "\n", v3)

[ 1  1  1 -1] 
 [ 1.  1. -2.  0.] 
 [0.08333333 2.08333333 1.08333333 3.25      ]


<font color='blue'> &#9989;**Do this:** Again, using Python, make the basis you found above **orthonormal**.

In [22]:
# Put your answer here
mag_v1 = np.sqrt(np.dot(v1,v1))
mag_v2 = np.sqrt(np.dot(v2, v2))
mag_v3 = np.sqrt(np.dot(v3, v3))

v1_hat = v1/mag_v1
v2_hat = v2/mag_v2
v3_hat = v3/mag_v3

print(v1_hat, "\n", v2_hat, "\n", v3_hat)

[ 0.5  0.5  0.5 -0.5] 
 [ 0.40824829  0.40824829 -0.81649658  0.        ] 
 [0.02077929 0.51948227 0.27013078 0.81039234]


<font color='blue'> &#9989;**Do this:** How different are the calculation by hand and by python?

The calculations by and and by python are the same.

<font color='blue'> &#9989;**Do this:** We will create a function that implements the Gram-Schmidt process:\
This function takes a $m \times n$ Matrix $A$ with **linearly independent** columns as input and returns an $m \times n$ Matrix $G$ with orthogonal column vectors. 
    
<font color='blue'> The basic algorithm works as follows:

- <font color='blue'>`AT = transpose(A)` (this process works with the columns of the matrix so it is easier to work with the transpose. Think about a list of lists, it is easy to get a row (a list)).  
- <font color='blue'> Make a new empty list of the same size as ```AT``` and call it ```GT``` (G transpose)
- <font color='blue'>Loop index ```i``` over all of the rows in AT (i.e. columns of A) 

    - <font color='blue'>GT[i] is set to be  AT[i]
    - <font color='blue'>Loop index ```j``` from 0 to ```i```
        - GT[i] -= projection of AT[i] onto GT[j]
        
        
- <font color='blue'>```G = transpose(GT)```

<font color='blue'>Use the above definition as a template:

In [115]:
def GramSchmidt(A):
    A = np.array(A, dtype=float)
    AT = A.T
    GT = np.zeros_like(AT)

    for i in range(AT.shape[0]):
        ui = AT[i].copy()

        for j in range(i):
            uj = GT[j]
            if np.dot(uj, uj) != 0:
                ui -= projection(ui, uj)

        GT[i] = ui

    return GT.T

<font color='blue'> &#9989;**Do this:** Test your function using the following sets of vectors `A2`, `A3`, and `A4`.

In [87]:
# A.
A2 = [[-4,-6],[3,5]]
GramSchmidt(A2)

# put your answer here

array([[-4.  ,  0.24],
       [ 3.  ,  0.32]])

In [88]:
#B. 
B3 = [[1,1,1],[1,1,-2],[0,2,-1]]
A3 = np.array(B3).T
GramSchmidt(A3)

# put your answer here

array([[ 1.,  1., -1.],
       [ 1.,  1.,  1.],
       [ 1., -2.,  0.]])

In [89]:
# C.
A4 = [[1,4,8],[2,0,1],[0,5,5],[3,8,6]]
GramSchmidt(A4)
# Put your answer here


array([[ 1.,  2.,  4.],
       [ 2., -4.,  1.],
       [ 0.,  5.,  0.],
       [ 3.,  2., -2.]])

<font color='blue'> &#9989;**Do this:** Now use your function on the following set of vectors `A5`. What goes wrong?

In [90]:
B5 = [[1,1,1], [2,2,2],[1,1,-2]]
A5 = np.array(B5).T
GramSchmidt(A5)

# Put your answer here

array([[ 1.,  0.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  0., -2.]])

<font color=green>**Comment**. Notice that the the function you created only works for linearly independent vectors. 
    
<font color='blue'> &#9989;**Do this:** Create a new function called ```generalGS``` that checks first if the given vectors are linearly independent. If they are not, it keeps the linearly independent and returns an orthogonal basis for the space they span. 

In [121]:
def generalGS(A):
    # Get the transpose of A
    A = np.array(A, dtype=float)
    AT = A.T

    # Use np.all() to delete the zero elements of AT (zero vectors)
    AT = AT[~np.all(AT == 0, axis=1)]
    
    # Set GT to be the first element of AT
    GT = AT[0].reshape(1, -1)
    
    # Keep a counter of the number of elements in GT. Currently we have 1.
    k = 1
    
    # Loop over the rows of AT
    for i in range(1, AT.shape[0]):
        proj = AT[i].copy()
        # Loop over the previous rows of GT to calculate the projection.
        for j in range(k):
            # Subtract the projection of AT[i] onto GT[j]
            proj -= projection(proj, GT[j])
        # If the element we got is not zero append it to the matrix.
        if not np.allclose(proj, np.zeros_like(proj)):   # to deal with approximations
            GT = np.append(GT, proj.reshape(1, -1), axis=0)
            k += 1
            
    # Transpose GT to get the orthogonal matrix G
    G = GT.T

    return G

<font color='blue'> &#9989;**Do this:** Use your `GeneralGS` function on the following sets of vectors `A6` and `A7`.

In [124]:
B6 = [[1,1,1], [2,2,2],[1,1,-2]]
A6 = np.array(B5).T
G6 = generalGS(A6)
G6

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1., -2.]])

In [125]:
A7=[[1,2],[1,1],[-1,1]]
G7 = generalGS(A7)
G7

array([[ 1.        ,  1.33333333],
       [ 1.        ,  0.33333333],
       [-1.        ,  1.66666667]])

---
## Congratulations, you're done!
## Before you close or submit this In-Class Assignment, please make sure of a few things:
- Did you save the file? `Ctrl + S` like everything else works!
- Is the file in correct format? You need to submit this file in `.pdf` format. To do so, `Ctrl + P` and `Save as pdf` (on Windows) or `command + P` in mac.
- If that does not work, please Google "ipynb to pdf converter" and that should do the job.
- Are the pictures/images rendering correctly in the `.pdf` format?
- If the images are not rendering, you could also use this command in a cell:

`from IPython.display import display, Image`

`display(Image(filename="a.jpg", height=400, width=400))`

THIS ONLY WORKS WITH JPGS.
- If this fails, save it as a pdf and merge it with this pdf, perhaps using an online tool (google it!)

- Please double check the contents of the file. One of the most common errors students make is submission of an empty file!